package:
    name: perl
    version: "5.20.2"

source:
    fn: perl-5.20.2.tar.gz
    url: http://www.cpan.org/src/5.0/perl-5.20.2.tar.gz

build:
    number: 0

about:
    home: http://www.cpan.org/src/README.html
