package:
  name: epics-synapps
  version: '20141009.1'

source:
  git_url: https://github.com/epicsdeb/synapps.git
  git_rev: 'debian/20141009-1'
  #git_rev: master

build:
  number: 10
  detect_binary_files_with_prefix: 1

requirements:
  build:
    - epics-base
    - readline

  run:
    - epics-base
    - readline

about:
    home: https://github.com/epicsdeb/synapps
    license: Epics Open License
    summary: synApps is a collection of software tools that help to create a control system for beamlines.  Based on BNL patched version.