package:
    name: perl
    version: "5.18.2"

source:
    fn: perl-5.18.2.tar.gz
    url: http://www.cpan.org/src/5.0/perl-5.18.2.tar.gz

build:
    number: 1

about:
    home: http://www.cpan.org/src/README.html
